name: CI automated testing

on: push

jobs:
  build-cyclone:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Cyclone
      uses: actions/checkout@v2
      with:
        repository: eclipse-cyclonedds/cyclonedds
        path: cyclonedds
        ref: idlcxx
        token: ${{ secrets.PAT }}

    - name: Check for Cyclone build cache
      id: cyclone-cache
      uses: actions/cache@v2
      with:
        path: cyclonedds
        key: ${{ runner.os }}-v2-${{ hashFiles('cyclonedds/.git/refs/heads/idlcxx') }}

    - name: Get Java and Maven
      if: steps.cyclone-cache.outputs.cache-hit != 'true'
      uses: actions/setup-java@v1
      with:
        java-version: '9'
        java-package: jdk
        architecture: x64 

    - name: Get latest CMake
      if: steps.cyclone-cache.outputs.cache-hit != 'true'
      uses: lukka/get-cmake@v3.19.1

    - name: Build Cyclone
      if: steps.cyclone-cache.outputs.cache-hit != 'true'
      run: |
        mkdir cyclonedds/build cyclonedds/install && cd cyclonedds/build
        cmake .. -DCMAKE_INSTALL_PREFIX=../install
        cmake --build . --target install

    - name: Build result
      uses: actions/upload-artifact@v2
      with:
        name: cyclone-build
        path: cyclonedds/install
    
  test:
    runs-on: ubuntu-latest
    needs: build-cyclone
    strategy:
      fail-fast: false
      matrix:
        python:
          - 3.6.12
          - 3.7.9
          - 3.9.0

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Cyclone
      uses: actions/download-artifact@v2
      with:
        name: cyclone-build
        path: cyclonedds/install

    - name: Get latest CMake
      if: steps.cyclone-cache.outputs.cache-hit != 'true'
      uses: lukka/get-cmake@v3.19.1
    
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: For python 3.6 we need backported dataclasses
      if: matrix.python == '3.6.12'
      run: pip install dataclasses

    - name: Install cdds
      working-directory: ./cdds
      run: |
        pip install -e . 
        pip install pytest pytest-cov flake8

    - name: Generate test module with idl
      working-directory: ./cdds/tests/support_modules/testtopics
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_PREFIX_PATH=${{ github.workspace }}/cyclonedds/install
        cmake --build .

    - name: Run tests
      working-directory: ./cdds
      run: pytest
      env:
        ddsc: ../cyclonedds/install/lib/libddsc.so